"""conectar foreign key group_members--comunity

Revision ID: 096184de2a84
Revises: 4bc148cf1c38
Create Date: 2025-12-15 19:32:10.446685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096184de2a84'
down_revision = '4bc148cf1c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'communities', ['community_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('community_id')

    # ### end Alembic commands ###
