"""nuevo chat!

Revision ID: 157f1d10ef85
Revises: cf9382761d5d
Create Date: 2025-11-28 19:03:09.093443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157f1d10ef85'
down_revision = 'cf9382761d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chat_id', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key(None, 'chats', ['chat_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('chat_id')

    # ### end Alembic commands ###
