"""add supabase_id to users

Revision ID: 1b71b9a8ec5e
Revises: feba93920dc2
Create Date: 2025-09-20 11:51:35.333428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b71b9a8ec5e'
down_revision = 'feba93920dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supabase_id', sa.UUID(), nullable=True))
        batch_op.create_unique_constraint(None, ['supabase_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('supabase_id')

    # ### end Alembic commands ###
