"""regenerar messeges

Revision ID: 1deb0205f473
Revises: 993a82d0539d
Create Date: 2025-12-21 11:43:04.081829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1deb0205f473'
down_revision = '993a82d0539d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.alter_column('community_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('app_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_group_messages_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_messages_community_id'), ['community_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('group_messages_app_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('group_messages_community_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'communities', ['community_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'apps', ['app_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('group_messages_community_id_fkey'), 'communities', ['community_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('group_messages_app_id_fkey'), 'apps', ['app_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_group_messages_community_id'))
        batch_op.drop_index(batch_op.f('ix_group_messages_app_id'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('app_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('community_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
