"""messege_type

Revision ID: 2054fb010166
Revises: a35013736fbd
Create Date: 2025-12-20 20:25:43.462026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2054fb010166'
down_revision = 'a35013736fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.drop_column('message_type')

    # ### end Alembic commands ###
