"""nuevo formulario create community

Revision ID: 26c0923b8699
Revises: d0e3b92fda88
Create Date: 2026-01-03 12:13:15.427966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c0923b8699'
down_revision = 'd0e3b92fda88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('allow_public_join', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('rules', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('max_admins', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_moderators', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('max_moderators')
        batch_op.drop_column('max_admins')
        batch_op.drop_column('rules')
        batch_op.drop_column('allow_public_join')
        batch_op.drop_column('is_public')
        batch_op.drop_column('cover_image_url')

    # ### end Alembic commands ###
