"""condifuraqcion chat dentro

Revision ID: 2f082e897462
Revises: 26c0923b8699
Create Date: 2026-01-03 13:01:19.748739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f082e897462'
down_revision = '26c0923b8699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_configured', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_column('team_configured')

    # ### end Alembic commands ###
