"""Añadir tablas Plan, UserPlan y QuizAnalytics

Revision ID: 47d2eed89ecc
Revises: a33777fc6127
Create Date: 2025-10-15 11:26:29.598065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d2eed89ecc'
down_revision = 'a33777fc6127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_pages_slug'), ['slug'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('current_plan_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('plan_expiration', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['stripe_customer_id'])
        batch_op.create_foreign_key(None, 'plans', ['current_plan_id'], ['id'])
        batch_op.drop_column('created_at timestamptz default now()')
        batch_op.drop_column('stripe_customer_id text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id text', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at timestamptz default now()', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('plan_expiration')
        batch_op.drop_column('current_plan_id')
        batch_op.drop_column('stripe_customer_id')

    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_slug'))
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
