"""Hello

Revision ID: 64ae767a0750
Revises: 4ae870bfa213
Create Date: 2025-12-06 11:55:15.213404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64ae767a0750'
down_revision = '4ae870bfa213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_reactions')
    op.drop_table('app_ratings')
    op.drop_table('poll_votes')
    op.drop_table('quiz_analytics')
    op.drop_table('app_analytics')
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('theme', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('creation_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('official_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=300), nullable=True))
        batch_op.drop_column('category')
        batch_op.drop_column('logo_url')
        batch_op.drop_column('website_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_url', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('logo_url', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('image_url')
        batch_op.drop_column('official_id')
        batch_op.drop_column('status')
        batch_op.drop_column('creation_date')
        batch_op.drop_column('theme')
        batch_op.drop_column('team')

    op.create_table('app_analytics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('active_users', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('new_members', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('messages_sent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('polls_created', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_reactions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_visits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('average_visit_duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], name=op.f('app_analytics_app_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('app_analytics_pkey'))
    )
    op.create_table('quiz_analytics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('clicks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('impresiones', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ctr', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('imagenes_usadas', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('quiz_analytics_plan_id_fkey')),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('quiz_analytics_quiz_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('quiz_analytics_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_analytics_pkey'))
    )
    op.create_table('poll_votes',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('option_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('voted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['group_messages.id'], name=op.f('poll_votes_message_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('poll_votes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('poll_votes_pkey'))
    )
    op.create_table('app_ratings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], name=op.f('app_ratings_app_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('app_ratings_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('app_ratings_pkey'))
    )
    op.create_table('message_reactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reaction_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['group_messages.id'], name=op.f('message_reactions_message_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('message_reactions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('message_reactions_pkey'))
    )
    # ### end Alembic commands ###
