"""add otp_secret

Revision ID: 6706a278c8c3
Revises: 018498c542f0
Create Date: 2025-08-31 11:47:58.642024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6706a278c8c3'
down_revision = '018498c542f0'
branch_labels = None
depends_on = None


def upgrade():
    # Añadir columna con valor por defecto temporal para usuarios existentes
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'otp_secret',
                sa.String(length=32),
                server_default='TEMPSECRET',
                nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('otp_secret')

    # ### end Alembic commands ###
