"""roles en el db

Revision ID: 790dee657852
Revises: 1deb0205f473
Create Date: 2025-12-21 11:54:55.101722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790dee657852'
down_revision = '1deb0205f473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
