"""empty message

Revision ID: 839384e102cf
Revises: 47d2eed89ecc
Create Date: 2025-11-01 12:34:58.229939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '839384e102cf'
down_revision = '47d2eed89ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
