"""cambios group_messeges 1

Revision ID: 993a82d0539d
Revises: a6ab59d80195
Create Date: 2025-12-21 11:32:34.675380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993a82d0539d'
down_revision = 'a6ab59d80195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.alter_column('community_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('app_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_group_messages_app_id'))
        batch_op.drop_index(batch_op.f('ix_group_messages_community_id'))
        batch_op.drop_constraint(batch_op.f('group_messages_community_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('group_messages_app_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'communities', ['community_id'], ['id'])
        batch_op.create_foreign_key(None, 'apps', ['app_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('group_messages_app_id_fkey'), 'apps', ['app_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('group_messages_community_id_fkey'), 'communities', ['community_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_group_messages_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_messages_app_id'), ['app_id'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('app_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('community_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('role')

    # ### end Alembic commands ###
