"""relacion duplicada app y reviews

Revision ID: a35013736fbd
Revises: db66cacbec28
Create Date: 2025-12-19 16:59:42.421417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35013736fbd'
down_revision = 'db66cacbec28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('reviews_app_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'apps', ['app_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reviews_app_id_fkey'), 'apps', ['app_id'], ['id'])

    # ### end Alembic commands ###
