"""helloooooooo

Revision ID: bf4992ba1a9e
Revises: a7c84cd341c0
Create Date: 2025-12-13 18:49:41.188962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4992ba1a9e'
down_revision = 'a7c84cd341c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('team')

    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint(batch_op.f('group_messages_app_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'communities', ['community_id'], ['id'])
        batch_op.drop_column('app_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('group_messages_app_id_fkey'), 'apps', ['app_id'], ['id'])
        batch_op.drop_column('community_id')

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
