"""hello23

Revision ID: c0caebfc6a64
Revises: d10ec1d3e5ad
Create Date: 2025-12-07 20:05:11.415628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0caebfc6a64'
down_revision = 'd10ec1d3e5ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_tags', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tags_app_id_fkey'), type_='foreignkey')
        batch_op.drop_column('app_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('tags_app_id_fkey'), 'apps', ['app_id'], ['id'])

    with op.batch_alter_table('app_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))

    # ### end Alembic commands ###
