"""actualizacion messeges

Revision ID: cf9382761d5d
Revises: d84b586cf947
Create Date: 2025-11-28 18:39:33.339605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf9382761d5d'
down_revision = 'd84b586cf947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=False))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('messages_recipient_id_fkey'), type_='foreignkey')
        batch_op.drop_column('read')
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('messages_recipient_id_fkey'), 'users', ['recipient_id'], ['id'])
        batch_op.alter_column('id',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('text')
        batch_op.drop_column('sender_name')

    # ### end Alembic commands ###
