"""añadido modelo de planes y suscripciones

Revision ID: d84b586cf947
Revises: 980decb921e4
Create Date: 2025-11-03 19:49:28.065047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd84b586cf947'
down_revision = '980decb921e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('renewal_date', sa.DateTime(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('notifications',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('notifications',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('user_plans', schema=None) as batch_op:
        batch_op.drop_column('renewal_date')

    # ### end Alembic commands ###
