"""new group messeges and members making community a dad table

Revision ID: db66cacbec28
Revises: f495827c614c
Create Date: 2025-12-19 16:53:47.872353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db66cacbec28'
down_revision = 'f495827c614c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_members_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_members_community_id'), ['community_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('group_members_app_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('group_members_community_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'apps', ['app_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'communities', ['community_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('verification_method')
        batch_op.drop_column('account_username')
        batch_op.drop_column('interests_data')
        batch_op.drop_column('usage_count')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('last_used_at')

    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_messages_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_messages_community_id'), ['community_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('group_messages_app_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('group_messages_community_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'communities', ['community_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'apps', ['app_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('poll_question')
        batch_op.drop_column('is_pinned')
        batch_op.drop_column('poll_options')
        batch_op.drop_column('message_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('poll_options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_pinned', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('poll_question', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('group_messages_community_id_fkey'), 'communities', ['community_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('group_messages_app_id_fkey'), 'apps', ['app_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_group_messages_community_id'))
        batch_op.drop_index(batch_op.f('ix_group_messages_app_id'))

    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('usage_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('interests_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('account_username', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('verification_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('group_members_community_id_fkey'), 'communities', ['community_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('group_members_app_id_fkey'), 'apps', ['app_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_group_members_community_id'))
        batch_op.drop_index(batch_op.f('ix_group_members_app_id'))

    # ### end Alembic commands ###
