"""relaciones reviews app

Revision ID: f495827c614c
Revises: 096184de2a84
Create Date: 2025-12-15 21:16:03.401139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f495827c614c'
down_revision = '096184de2a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('app_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('app_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
