"""nuveo security_logs

Revision ID: fbb06d1b9b52
Revises: a3be7118f057
Create Date: 2025-11-02 12:34:27.417980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb06d1b9b52'
down_revision = 'a3be7118f057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('security_logs', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
