"""add slug to quizzes and blogst

Revision ID: feba93920dc2
Revises: 6706a278c8c3
Create Date: 2025-08-31 17:24:52.030733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feba93920dc2'
down_revision = '6706a278c8c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogst', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_blogst_slug'), ['slug'], unique=True)

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_quizzes_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quizzes_slug'))
        batch_op.drop_column('slug')

    with op.batch_alter_table('blogst', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blogst_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
